[project]
name = "api"
version = "0.1.0"
description = "API for the knowledge-focus project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "uvicorn>=0.29.0",
]
